Repository ESmartGreenHouse/smartgreenhouse_app, pull requests merged in 2021-01, with the labels that each got.

#8 Firestore
  firebase.json
  firestore.indexes.json
  firestore.rules
  lib/app.dart
  lib/particles/cubit/particles_cubit.dart
  packages/authentication_repository/pubspec.lock
  packages/greenhouse_repository/lib/src/greenhouse_repository.dart
Labels: preview

#9 Particles
  README.md
  firestore.rules
  images/cloud.jpg
  lib/alerts/alerts.dart
  lib/alerts/view/alerts_page.dart
  lib/alerts/view/view.dart
  lib/app.dart
  lib/common/text_dialog.dart
  lib/home/view/home_page.dart
  lib/login/cubit/login_cubit.dart
  lib/login/view/login_form.dart
  lib/login/view/login_page.dart
  lib/logout/view/logout_button.dart
  lib/main.dart
  lib/menu/view/app_drawer.dart
  lib/particle_cloud/cubit/particle_cloud_cubit.dart
  lib/particle_cloud/cubit/particle_cloud_state.dart
  lib/particle_cloud/models/client_id.dart
  lib/particle_cloud/models/client_secret.dart
  lib/particle_cloud/models/cloud_password.dart
  lib/particle_cloud/models/models.dart
  lib/particle_cloud/particle_cloud.dart
  lib/particle_cloud/view/particle_cloud_button.dart
  lib/particle_cloud/view/particle_cloud_form.dart
  lib/particle_cloud/view/particle_cloud_page.dart
  lib/particle_cloud/view/view.dart
  lib/particles/cubit/particles_cubit.dart
  lib/particles/view/particles_page.dart
  lib/particles/view/uid_dialog.dart
  lib/particles/view/view.dart
  lib/reports/cubit/reports_cubit.dart
  lib/reports/cubit/reports_state.dart
  lib/reports/view/points_line_chart.dart
  lib/reports/view/reports_page.dart
  lib/reports/view/reports_sensor_list.dart
  lib/reports/view/view.dart
  lib/reports_picker/cubit/reports_picker_cubit.dart
  lib/reports_picker/cubit/reports_picker_state.dart
  lib/reports_picker/reports_picker.dart
  lib/reports_picker/view/reports_picker.dart
  lib/reports_picker/view/reports_picker_date.dart
  lib/reports_picker/view/reports_picker_sensor.dart
  lib/reports_picker/view/reports_picker_time.dart
  lib/reports_picker/view/view.dart
  lib/splash/view/splash_page.dart
  packages/authentication_repository/lib/src/authentication_repository.dart
  packages/authentication_repository/lib/src/models/user.dart
  packages/authentication_repository/pubspec.lock
  packages/authentication_repository/pubspec.yaml
  packages/greenhouse_repository/lib/src/greenhouse_repository.dart
  packages/greenhouse_repository/lib/src/models/particle.dart
  packages/greenhouse_repository/pubspec.lock
  packages/greenhouse_repository/pubspec.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement, preview

#11 Create LICENSE
  LICENSE
Labels: documentation
